### ISSUE TITLE
why is a virtualenv checked in?

### ISSUE THREAD

**Issue by stevemart** [IBM/OpenWhiskChatAssistant#4]
The entire https://github.com/IBM/OpenWhiskChatAssistant/tree/master/API_Encapsulation/virtualenv should be deleted

**Comment by markstur** [comment]
FYI -- the python .gitignore might help avoid future mistakes like this (but it only would've caught venv not virtualenv).  https://github.com/github/gitignore/blob/master/Python.gitignore

**Comment by daisy-ycguo** [comment]
Close as fixed.
